### ISSUE TITLE
Example Link not working

### ISSUE THREAD

**Issue by velcrome** [vvvvpm/vpm#1]
![image](https://cloud.githubusercontent.com/assets/280537/15638279/c5696774-261e-11e6-9bcb-5ca37e2cc4b7.png)

seem to be 2 issues here,
first it does not find the vvvv dir, even though i did the full routine incl. admin fallback.
second, it seems not to like the .vpack when using the link copied from your vvvv description page

conceptually it looks really cool, btw!

**Comment by velcrome** [comment]
update:
using any of the vpms:// urls provided work great

is it always safe to rename https to vpms?

**Comment by microdee** [comment]
it should be always safe to replace https:// to vpms://. yeah it doesn't support plain http url's yet, it's pretty simple to implement so that's coming soon too.
If it wouldn't find vvvv it would tell that it couldn't fetch a vvvv from registry. Maybe that status message will get a friendlier tone.

**Comment by velcrome** [comment]
page with faulty links seems to be gone. 
closing this, as it is no longer reproducible ;)
