### ISSUE TITLE
Browser engine out of date

### ISSUE THREAD

**Issue by phlegma** [vvvvpm/vpm#10]
licence window shows error message from github. 

![Desktop 2019-04-03 12 31 45](https://user-images.githubusercontent.com/358332/55472537-a804e480-560c-11e9-85db-6943017a3065.png)

**Comment by fibo** [comment]
@phlegma are you using IE? If yes, since Microsoft adquired GitHub, it is really fun!

**Comment by phlegma** [comment]
@fibo i think there the licence view is based on chromium.
<package id="CefSharp.Common" version="57.0.0" targetFramework="net461" />
<package id="CefSharp.Wpf" version="57.0.0" targetFramework="net461" />
and needs and update. latest version of ChromiumSharp is 71.0.3578.98.

**Comment by microdee** [comment]
license page no longer a thing, closed the issue
