### ISSUE TITLE
Cleanup() throws IOException

### ISSUE THREAD

**Issue by velcrome** [vvvvpm/vpm#2]
![image](https://cloud.githubusercontent.com/assets/280537/17306403/33b777fa-5830-11e6-80cb-eb54e89a940f.png)

maybe some file handle  not closed properly?

edit: Exception translates to 

> IOException: The process cannot access the file 'file path' because it is being used by another process

**Comment by microdee** [comment]
fixed in theory in last release on contrib page 1.0.2. before archive was not released manually only with GC so if .vpm folder is deleted before that you get this error. now archives are released manually.
